/**
 * Interface representing the call transcript data structure from JSON files
 */
export interface CallTranscriptRaw {
  customer_name: string;
  customer_unique_id: string;
  support_agent_name: string;
  support_agent_id: string;
  call_transcript: string;
  overall_satisfaction_score: number;
  category_of_call: string;
  call_duration: number;
  call_date_time: string;
  call_resolution_status: string;
  escalation_level: string;
  follow_up_required: string;
  customer_tier: string;
  issue_severity: string;
  agent_experience_level: string;
  customer_previous_contact_count: number;
}

/**
 * Interface representing a call transcript record in the database
 * Extends the raw data with an ID field for the primary key
 */
export interface CallTranscript extends CallTranscriptRaw {
  id: number;
}

/**
 * Type for creating a new call transcript record
 * Omits the ID as it will be auto-generated by the database
 */
export type CreateCallTranscriptDto = CallTranscriptRaw;

/**
 * Type for updating an existing call transcript record
 * Makes all fields optional
 */
export type UpdateCallTranscriptDto = Partial<CallTranscriptRaw>;
